### ISSUE TITLE
bunq_setup.py error Key error

### ISSUE THREAD

**Issue by blackspeck** [noahvanes/bunq-python-server#1]
When i start the bunq_setup.py i get following error.

`/home/Blackspeck/.virtualenvs/my-virtualenv/lib/python3.6/site-packages/bunq/sdk/json/converter.py:391: UserWarning: [bunq SDK beta] Key "document_front_attachment" in "UserPerson" is unknown.

  warnings.warn(cls._WARNING_KEY_UNKNOWN.format(key, context_name))
/home/Blackspeck/.virtualenvs/my-virtualenv/lib/python3.6/site-packages/bunq/sdk/json/converter.py:391: UserWarning: [bunq SDK beta] Key "document_back_attachment" in "UserPerson" is unknown.

  warnings.warn(cls._WARNING_KEY_UNKNOWN.format(key, context_name))
/home/Blackspeck/.virtualenvs/my-virtualenv/lib/python3.6/site-packages/bunq/sdk/json/converter.py:391: UserWarning: [bunq SDK beta] Key "flarum_username" in "UserPerson" is unknown.

  warnings.warn(cls._WARNING_KEY_UNKNOWN.format(key, context_name))
/home/Blackspeck/.virtualenvs/my-virtualenv/lib/python3.6/site-packages/bunq/sdk/json/converter.py:391: UserWarning: [bunq SDK beta] Key "customer" in "UserPerson" is unknown.

  warnings.warn(cls._WARNING_KEY_UNKNOWN.format(key, context_name))
/home/Blackspeck/.virtualenvs/my-virtualenv/lib/python3.6/site-packages/bunq/sdk/json/converter.py:391: UserWarning: [bunq SDK beta] Key "customer_limit" in "UserPerson" is unknown.

  warnings.warn(cls._WARNING_KEY_UNKNOWN.format(key, context_name))
/home/Blackspeck/.virtualenvs/my-virtualenv/lib/python3.6/site-packages/bunq/sdk/json/converter.py:391: UserWarning: [bunq SDK beta] Key "billing_contract" in "UserPerson" is unknown.

  warnings.warn(cls._WARNING_KEY_UNKNOWN.format(key, context_name))
/home/Blackspeck/.virtualenvs/my-virtualenv/lib/python3.6/site-packages/bunq/sdk/json/converter.py:391: UserWarning: [bunq SDK beta] Key "pack_membership" in "UserPerson" is unknown.

  warnings.warn(cls._WARNING_KEY_UNKNOWN.format(key, context_name))
/home/Blackspeck/.virtualenvs/my-virtualenv/lib/python3.6/site-packages/bunq/sdk/json/converter.py:391: UserWarning: [bunq SDK beta] Key "joint_membership" in "UserPerson" is unknown.

  warnings.warn(cls._WARNING_KEY_UNKNOWN.format(key, context_name))
/home/Blackspeck/.virtualenvs/my-virtualenv/lib/python3.6/site-packages/bunq/sdk/json/converter.py:391: UserWarning: [bunq SDK beta] Key "premium_trial" in "UserPerson" is unknown.

  warnings.warn(cls._WARNING_KEY_UNKNOWN.format(key, context_name))`

**Comment by noahvanes** [comment]
These warnings are expected, and should not cause any issues ...

**Comment by blackspeck** [comment]
oh ok :) thanks
